// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using examen_csharp_sur_table.Data;

#nullable disable

namespace examen_csharp_sur_table.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260109112042_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("examen_csharp_sur_table.Models.AnneeScolaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AnneesScolaires");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "2023-2024",
                            Libelle = "Année Scolaire 2023-2024",
                            Statut = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "2024-2025",
                            Libelle = "Année Scolaire 2024-2025",
                            Statut = 0
                        });
                });

            modelBuilder.Entity("examen_csharp_sur_table.Models.Classe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "L1-INFO",
                            Libelle = "Licence 1 Informatique"
                        },
                        new
                        {
                            Id = 2,
                            Code = "L2-INFO",
                            Libelle = "Licence 2 Informatique"
                        },
                        new
                        {
                            Id = 3,
                            Code = "M1-MIAGE",
                            Libelle = "Master 1 MIAGE"
                        });
                });

            modelBuilder.Entity("examen_csharp_sur_table.Models.Etudiant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Etudiants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Matricule = "STD001",
                            Nom = "Diallo",
                            Prenom = "Moussa"
                        },
                        new
                        {
                            Id = 2,
                            Matricule = "STD002",
                            Nom = "Ndiaye",
                            Prenom = "Fatou"
                        },
                        new
                        {
                            Id = 3,
                            Matricule = "STD003",
                            Nom = "Sow",
                            Prenom = "Amadou"
                        },
                        new
                        {
                            Id = 4,
                            Matricule = "STD004",
                            Nom = "Ba",
                            Prenom = "Aïssatou"
                        },
                        new
                        {
                            Id = 5,
                            Matricule = "STD005",
                            Nom = "Traore",
                            Prenom = "Ibrahima"
                        });
                });

            modelBuilder.Entity("examen_csharp_sur_table.Models.Inscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnneeScolaireId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClasseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("EtudiantId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Montant")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.HasIndex("ClasseId");

                    b.HasIndex("EtudiantId");

                    b.ToTable("Inscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnneeScolaireId = 2,
                            ClasseId = 1,
                            Date = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EtudiantId = 1,
                            Montant = 50000.00m
                        },
                        new
                        {
                            Id = 2,
                            AnneeScolaireId = 2,
                            ClasseId = 1,
                            Date = new DateTime(2024, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EtudiantId = 2,
                            Montant = 50000.00m
                        },
                        new
                        {
                            Id = 3,
                            AnneeScolaireId = 2,
                            ClasseId = 2,
                            Date = new DateTime(2024, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EtudiantId = 3,
                            Montant = 55000.00m
                        },
                        new
                        {
                            Id = 4,
                            AnneeScolaireId = 2,
                            ClasseId = 3,
                            Date = new DateTime(2024, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EtudiantId = 4,
                            Montant = 60000.00m
                        },
                        new
                        {
                            Id = 5,
                            AnneeScolaireId = 1,
                            ClasseId = 1,
                            Date = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EtudiantId = 5,
                            Montant = 50000.00m
                        });
                });

            modelBuilder.Entity("examen_csharp_sur_table.Models.Inscription", b =>
                {
                    b.HasOne("examen_csharp_sur_table.Models.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Inscriptions")
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("examen_csharp_sur_table.Models.Classe", "Classe")
                        .WithMany("Inscriptions")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("examen_csharp_sur_table.Models.Etudiant", "Etudiant")
                        .WithMany("Inscriptions")
                        .HasForeignKey("EtudiantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");

                    b.Navigation("Classe");

                    b.Navigation("Etudiant");
                });

            modelBuilder.Entity("examen_csharp_sur_table.Models.AnneeScolaire", b =>
                {
                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("examen_csharp_sur_table.Models.Classe", b =>
                {
                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("examen_csharp_sur_table.Models.Etudiant", b =>
                {
                    b.Navigation("Inscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
